Repository depromeet/EggPotato_Study, pull requests merged in 2022-11, with the labels that each got.

#5 [정대윤] WEEK 1 🐑 & 🐺
  JeongMeoYoon/WEEK1.js
Labels: 프로그래머스

#9 [김해나] WEEK4
  김해나/src/WEEK1.python
  김해나/src/WEEK4.python
Labels: 백준

#10 [정대윤] Week4
  JeongMeoYoon/WEEK2-puyo-puyo.js
  JeongMeoYoon/WEEK2.java
  JeongMeoYoon/WEEK2.js
Labels: 프로그래머스, 백준

#7 [김가은] WEEK4
  김가은/WEEK4.js
  김가은/example.txt
  김가은/template.js
Labels: 백준

#11 [김가은] WEEK5
  김가은/WEEK5.js
  김가은/WEEK6.js
Labels: 프로그래머스

#8 [이제준] WEEK3 WEEK4
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  EggPotato_Study.iml
  이제준/src/WEEK3.java
  이제준/src/WEEK4.java
Labels: 프로그래머스, 백준

#12 [정대윤] WEEK 5
  JeongMeoYoon/WEEK5.js
Labels: 프로그래머스

#13 [김가은] WEEK6 🪺
  김가은/WEEK6.js
Labels: 프로그래머스

#14 [정대윤] week6
  JeongMeoYoon/WEEK6.js
Labels: 프로그래머스

#16 [이성태] WEEK6
  이성태/WEEK6/주차 요금 계산.py
Labels: 프로그래머스

#18 [김가은] WEEK7 🪅
  김가은/WEE7.js
Labels: 프로그래머스
